import AppKit
import Foundation

public enum PasteboardAccessState: String, Codable, Equatable, Sendable {
    case unknown
    case allowed
    case denied
}

public enum PasteboardSkipReason: String, Codable, Equatable, Sendable {
    case accessDenied
    case empty
    case unsupported
    case malformed
    case privacyMarker
    case changedDuringRead
}

public enum PasteboardReadResult: Equatable, Sendable {
    case snapshot(PasteboardSnapshot)
    case skipped(PasteboardSkipReason)
}

public enum PasteboardWriteResult: Equatable, Sendable {
    case written(changeCount: Int)
    case failed
    case changedDuringWrite
}

public struct PasteboardSnapshot: Codable, Equatable, Hashable, Sendable {
    public let changeCount: Int
    public let capture: ClipboardCapture

    public init(changeCount: Int, capture: ClipboardCapture) {
        self.changeCount = changeCount
        self.capture = capture
    }
}

/// Marker identifiers used by password managers, text expanders, and other tools to
/// identify data that should not enter clipboard history.  Markers are checked before
/// reading text or URL payload bytes.
public enum ClipboardPrivacyMarkers {
    public static let transient = "org.nspasteboard.TransientType"
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    public static let ignoredTypeIdentifiers: Set<String> = [
        transient,
        concealed,
        autoGenerated,
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    ]
}

/// The AppKit edge is isolated to the main actor.  Tests can implement this protocol
/// with a named private pasteboard fixture or with an entirely in-memory fixture.
@MainActor
public protocol ClipboardPasteboard: AnyObject {
    var changeCount: Int { get }
    var accessState: PasteboardAccessState { get }

    func readSnapshotIfStable(expectedChangeCount: Int) -> PasteboardReadResult
    func write(payload: ClipboardPayload) -> PasteboardWriteResult
}

/// Main-actor adapter around a concrete NSPasteboard.  The app should pass
/// `NSPasteboard.general` in production; tests should use a uniquely named board.
@MainActor
public final class NSPasteboardBoundary: ClipboardPasteboard {
    private let pasteboard: NSPasteboard
    private let sourceProvider: () -> ClipboardSource?
    private let accessBehaviorProvider: () -> NSPasteboard.AccessBehavior

    public init(
        pasteboard: NSPasteboard,
        sourceProvider: @escaping () -> ClipboardSource? = { nil },
        accessBehaviorProvider: (() -> NSPasteboard.AccessBehavior)? = nil
    ) {
        self.pasteboard = pasteboard
        self.sourceProvider = sourceProvider
        self.accessBehaviorProvider = accessBehaviorProvider ?? { pasteboard.accessBehavior }
    }

    public convenience init(
        name: NSPasteboard.Name,
        sourceProvider: @escaping () -> ClipboardSource? = { nil }
    ) {
        self.init(pasteboard: NSPasteboard(name: name), sourceProvider: sourceProvider)
    }

    public static func general(
        sourceProvider: @escaping () -> ClipboardSource? = { nil }
    ) -> NSPasteboardBoundary {
        NSPasteboardBoundary(pasteboard: .general, sourceProvider: sourceProvider)
    }

    public var changeCount: Int {
        pasteboard.changeCount
    }

    /// `accessBehavior` is metadata, so this reports access policy changes without
    /// triggering a pasteboard payload read or waiting for a new change count.
    public var accessState: PasteboardAccessState {
        switch accessBehaviorProvider() {
        case .alwaysDeny:
            .denied
        case .alwaysAllow:
            .allowed
        case .ask, .default:
            .unknown
        @unknown default:
            .unknown
        }
    }

    public func readSnapshotIfStable(expectedChangeCount: Int) -> PasteboardReadResult {
        guard expectedChangeCount == pasteboard.changeCount else {
            return .skipped(.changedDuringRead)
        }

        if pasteboard.accessBehavior == .alwaysDeny {
            return .skipped(.accessDenied)
        }

        guard let item = pasteboard.pasteboardItems?.first else {
            if pasteboard.accessBehavior == .alwaysDeny {
                return .skipped(.accessDenied)
            }
            return .skipped(.empty)
        }

        let initialTypes = item.types
        guard !initialTypes.isEmpty else {
            return .skipped(.unsupported)
        }

        let initialTypeIdentifiers = initialTypes.map(\.rawValue)
        if initialTypeIdentifiers.contains(where: ClipboardPrivacyMarkers.ignoredTypeIdentifiers.contains) {
            return .skipped(.privacyMarker)
        }

        let source = source(for: item)
        let captureResult = capture(item: item, types: initialTypes, source: source)

        guard expectedChangeCount == pasteboard.changeCount else {
            return .skipped(.changedDuringRead)
        }

        let finalTypeIdentifiers = item.types.map(\.rawValue)
        if finalTypeIdentifiers.contains(where: ClipboardPrivacyMarkers.ignoredTypeIdentifiers.contains) {
            return .skipped(.privacyMarker)
        }

        guard initialTypeIdentifiers == finalTypeIdentifiers else {
            return .skipped(.changedDuringRead)
        }

        switch captureResult {
        case .snapshot(let snapshot):
            return .snapshot(snapshot)
        case .skipped(let reason):
            return .skipped(reason)
        }
    }

    public func write(payload: ClipboardPayload) -> PasteboardWriteResult {
        // Reject a malformed empty restore before changing the user's clipboard.
        guard !payload.representations.isEmpty || payload.plainText != nil || payload.url != nil else {
            return .failed
        }

        let writeChangeCount = pasteboard.prepareForNewContents(with: [.currentHostOnly])
        var didWrite = true

        for representation in payload.representations {
            let type = NSPasteboard.PasteboardType(representation.typeIdentifier)
            didWrite = pasteboard.setData(representation.data, forType: type) && didWrite
        }

        if payload.representations.isEmpty {
            if let url = payload.url {
                didWrite = pasteboard.setString(url.absoluteString, forType: .URL) && didWrite
                if let text = payload.plainText {
                    didWrite = pasteboard.setString(text, forType: .string) && didWrite
                }
            } else if let text = payload.plainText {
                didWrite = pasteboard.setString(text, forType: .string) && didWrite
            } else {
                didWrite = false
            }
        }

        guard didWrite else {
            return .failed
        }

        guard pasteboard.changeCount == writeChangeCount else {
            return .changedDuringWrite
        }

        return .written(changeCount: writeChangeCount)
    }

    private func source(for item: NSPasteboardItem) -> ClipboardSource? {
        let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
        guard let markerBundleID = item.string(forType: sourceType), !markerBundleID.isEmpty else {
            return sourceProvider()
        }

        let provided = sourceProvider()
        return ClipboardSource(appName: provided?.appName, bundleIdentifier: markerBundleID)
    }

    private func capture(
        item: NSPasteboardItem,
        types: [NSPasteboard.PasteboardType],
        source: ClipboardSource?
    ) -> PasteboardReadResult {
        let availableTypeIdentifiers = types.map(\.rawValue)
        let urlType = types.first(where: { $0.rawValue == NSPasteboard.PasteboardType.URL.rawValue })
        let textType = types.first(where: { $0.rawValue == NSPasteboard.PasteboardType.string.rawValue })

        if let urlType {
            let urlText = item.string(forType: urlType)
                ?? (item.propertyList(forType: urlType) as? String)
                ?? (item.propertyList(forType: urlType) as? URL)?.absoluteString
            if let urlText, let url = validURL(from: urlText) {
                var representations = [ClipboardRepresentation]()
                if let data = item.data(forType: urlType) {
                    representations.append(ClipboardRepresentation(typeIdentifier: urlType.rawValue, data: data))
                } else {
                    representations.append(ClipboardRepresentation(typeIdentifier: urlType.rawValue, data: Data(urlText.utf8)))
                }

                var plainText: String?
                if let textType, let text = item.string(forType: textType) {
                    plainText = text
                    let data = item.data(forType: textType) ?? Data(text.utf8)
                    representations.append(ClipboardRepresentation(typeIdentifier: textType.rawValue, data: data))
                }

                let payload = ClipboardPayload(
                    primaryTypeIdentifier: urlType.rawValue,
                    representations: representations,
                    availableTypeIdentifiers: availableTypeIdentifiers,
                    plainText: plainText,
                    url: url
                )
                let capture = ClipboardCapture(
                    payload: payload,
                    primaryType: .url,
                    searchableText: plainText ?? url.absoluteString,
                    source: source
                )
                return .snapshot(PasteboardSnapshot(changeCount: pasteboard.changeCount, capture: capture))
            }
        }

        if let textType {
            guard let text = item.string(forType: textType) else {
                return .skipped(.malformed)
            }
            guard !text.isEmpty else {
                return .skipped(.empty)
            }

            let data = item.data(forType: textType) ?? Data(text.utf8)
            let payload = ClipboardPayload(
                primaryTypeIdentifier: textType.rawValue,
                representations: [ClipboardRepresentation(typeIdentifier: textType.rawValue, data: data)],
                availableTypeIdentifiers: availableTypeIdentifiers,
                plainText: text,
                url: validURL(from: text)
            )
            let isURL = validURL(from: text) != nil
            let capture = ClipboardCapture(
                payload: payload,
                primaryType: isURL ? .url : .text,
                searchableText: text,
                source: source
            )
            return .snapshot(PasteboardSnapshot(changeCount: pasteboard.changeCount, capture: capture))
        }

        if urlType != nil {
            return .skipped(.malformed)
        }
        return .skipped(.unsupported)
    }

    private func validURL(from string: String) -> URL? {
        guard let url = URL(string: string),
              let scheme = url.scheme,
              !scheme.isEmpty
        else {
            return nil
        }
        return url
    }
}
