import AppKit
import Foundation

public enum PasteboardAccessState: String, Codable, Equatable, Sendable {
    case unknown
    case allowed
    case denied
}

public enum PasteboardSkipReason: String, Codable, Equatable, Sendable {
    case accessDenied
    case empty
    case unsupported
    case malformed
    case privacyMarker
    case changedDuringRead
}

public enum PasteboardReadResult: Equatable, Sendable {
    case snapshot(PasteboardSnapshot)
    case skipped(PasteboardSkipReason)
}

public enum PasteboardWriteResult: Equatable, Sendable {
    case written(changeCount: Int)
    case failed
    case changedDuringWrite
}

public struct PasteboardSnapshot: Codable, Equatable, Hashable, Sendable {
    public let changeCount: Int
    public let capture: ClipboardCapture

    public init(changeCount: Int, capture: ClipboardCapture) {
        self.changeCount = changeCount
        self.capture = capture
    }
}

/// Marker identifiers used by password managers, text expanders, and other tools to
/// identify data that should not enter clipboard history.  Markers are checked before
/// reading text or URL payload bytes.
public enum ClipboardPrivacyMarkers {
    public static let transient = "org.nspasteboard.TransientType"
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    public static let ignoredTypeIdentifiers: Set<String> = [
        transient,
        concealed,
        autoGenerated,
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    ]
}

/// The AppKit edge is isolated to the main actor.  Tests can implement this protocol
/// with a named private pasteboard fixture or with an entirely in-memory fixture.
@MainActor
public protocol ClipboardPasteboard: AnyObject {
    var changeCount: Int { get }
    var accessState: PasteboardAccessState { get }

    func readSnapshotIfStable(expectedChangeCount: Int) -> PasteboardReadResult
    func write(payload: ClipboardPayload) -> PasteboardWriteResult
    func setExcludedBundleIdentifiers(_ identifiers: Set<String>)
}

/// Main-actor adapter around a concrete NSPasteboard.  The app should pass
/// `NSPasteboard.general` in production; tests should use a uniquely named board.
@MainActor
public final class NSPasteboardBoundary: ClipboardPasteboard {
    private let pasteboard: NSPasteboard
    private let sourceProvider: () -> ClipboardSource?
    private let accessBehaviorProvider: () -> NSPasteboard.AccessBehavior
    private var excludedBundleIdentifiers: Set<String> = []

    public init(
        pasteboard: NSPasteboard,
        sourceProvider: @escaping () -> ClipboardSource? = { nil },
        accessBehaviorProvider: (() -> NSPasteboard.AccessBehavior)? = nil
    ) {
        self.pasteboard = pasteboard
        self.sourceProvider = sourceProvider
        self.accessBehaviorProvider = accessBehaviorProvider ?? { pasteboard.accessBehavior }
    }

    public convenience init(
        name: NSPasteboard.Name,
        sourceProvider: @escaping () -> ClipboardSource? = { nil }
    ) {
        self.init(pasteboard: NSPasteboard(name: name), sourceProvider: sourceProvider)
    }

    public static func general(
        sourceProvider: @escaping () -> ClipboardSource? = { nil }
    ) -> NSPasteboardBoundary {
        NSPasteboardBoundary(pasteboard: .general, sourceProvider: sourceProvider)
    }

    public var changeCount: Int {
        pasteboard.changeCount
    }

    public func setExcludedBundleIdentifiers(_ identifiers: Set<String>) {
        excludedBundleIdentifiers = identifiers
    }

    /// `accessBehavior` is metadata, so this reports access policy changes without
    /// triggering a pasteboard payload read or waiting for a new change count.
    public var accessState: PasteboardAccessState {
        switch accessBehaviorProvider() {
        case .alwaysDeny:
            .denied
        case .alwaysAllow:
            .allowed
        case .ask, .default:
            .unknown
        @unknown default:
            .unknown
        }
    }

    public func readSnapshotIfStable(expectedChangeCount: Int) -> PasteboardReadResult {
        guard expectedChangeCount == pasteboard.changeCount else {
            return .skipped(.changedDuringRead)
        }

        if pasteboard.accessBehavior == .alwaysDeny {
            return .skipped(.accessDenied)
        }

        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            if pasteboard.accessBehavior == .alwaysDeny {
                return .skipped(.accessDenied)
            }
            return .skipped(.empty)
        }

        let initialTypesByItem = items.map(\.types)
        guard initialTypesByItem.allSatisfy({ !$0.isEmpty }) else {
            return .skipped(.unsupported)
        }

        let initialTypeIdentifiersByItem = initialTypesByItem.map { $0.map(\.rawValue) }
        if initialTypeIdentifiersByItem.joined().contains(where: ClipboardPrivacyMarkers.ignoredTypeIdentifiers.contains) {
            return .skipped(.privacyMarker)
        }

        let sourceMetadata = sourceMetadata(for: items)
        if !excludedBundleIdentifiers.isDisjoint(with: sourceMetadata.bundleIdentifiers) {
            return .skipped(.privacyMarker)
        }

        let captureResult = capture(items: items, typesByItem: initialTypesByItem, source: sourceMetadata.displaySource)

        guard expectedChangeCount == pasteboard.changeCount else {
            return .skipped(.changedDuringRead)
        }

        let finalTypeIdentifiersByItem = items.map { $0.types.map(\.rawValue) }
        if finalTypeIdentifiersByItem.joined().contains(where: ClipboardPrivacyMarkers.ignoredTypeIdentifiers.contains) {
            return .skipped(.privacyMarker)
        }

        guard initialTypeIdentifiersByItem == finalTypeIdentifiersByItem else {
            return .skipped(.changedDuringRead)
        }

        switch captureResult {
        case .snapshot(let snapshot):
            return .snapshot(snapshot)
        case .skipped(let reason):
            return .skipped(reason)
        }
    }

    public func write(payload: ClipboardPayload) -> PasteboardWriteResult {
        if let items = payload.items {
            return write(items: items)
        }

        // Reject a malformed empty restore before changing the user's clipboard.
        guard !payload.representations.isEmpty || payload.plainText != nil || payload.url != nil else {
            return .failed
        }

        let writeChangeCount = pasteboard.prepareForNewContents(with: [.currentHostOnly])
        var didWrite = true

        for representation in payload.representations {
            let type = NSPasteboard.PasteboardType(representation.typeIdentifier)
            didWrite = pasteboard.setData(representation.data, forType: type) && didWrite
        }

        if payload.representations.isEmpty {
            if let url = payload.url {
                didWrite = pasteboard.setString(url.absoluteString, forType: .URL) && didWrite
                if let text = payload.plainText {
                    didWrite = pasteboard.setString(text, forType: .string) && didWrite
                }
            } else if let text = payload.plainText {
                didWrite = pasteboard.setString(text, forType: .string) && didWrite
            } else {
                didWrite = false
            }
        }

        guard didWrite else {
            return .failed
        }

        guard pasteboard.changeCount == writeChangeCount else {
            return .changedDuringWrite
        }

        return .written(changeCount: writeChangeCount)
    }

    private func write(items: [ClipboardPayloadItem]) -> PasteboardWriteResult {
        guard !items.isEmpty else {
            return .failed
        }

        let pasteboardItems = items.compactMap(makePasteboardItem)
        guard pasteboardItems.count == items.count else {
            return .failed
        }

        let writeChangeCount = pasteboard.prepareForNewContents(with: [.currentHostOnly])
        guard pasteboard.writeObjects(pasteboardItems) else {
            return .failed
        }

        guard pasteboard.changeCount == writeChangeCount else {
            return .changedDuringWrite
        }
        return .written(changeCount: writeChangeCount)
    }

    private func makePasteboardItem(_ payload: ClipboardPayloadItem) -> NSPasteboardItem? {
        guard !payload.representations.isEmpty || payload.plainText != nil || payload.url != nil else {
            return nil
        }

        let item = NSPasteboardItem()
        for representation in payload.representations {
            guard item.setData(representation.data, forType: NSPasteboard.PasteboardType(representation.typeIdentifier)) else {
                return nil
            }
        }

        if payload.representations.isEmpty {
            if let url = payload.url {
                guard item.setString(url.absoluteString, forType: .URL) else {
                    return nil
                }
                if let plainText = payload.plainText,
                   !item.setString(plainText, forType: .string)
                {
                    return nil
                }
            } else if let plainText = payload.plainText {
                guard item.setString(plainText, forType: .string) else {
                    return nil
                }
            }
        }

        return item
    }

    private func sourceMetadata(for items: [NSPasteboardItem]) -> SourceMetadata {
        let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
        let markerBundleIdentifiers = items.compactMap { item in
            item.string(forType: sourceType).flatMap { $0.isEmpty ? nil : $0 }
        }
        let provided = sourceProvider()
        var bundleIdentifiers = Set(markerBundleIdentifiers)
        if let bundleIdentifier = provided?.bundleIdentifier {
            bundleIdentifiers.insert(bundleIdentifier)
        }

        guard let markerBundleID = markerBundleIdentifiers.first else {
            return SourceMetadata(displaySource: provided, bundleIdentifiers: bundleIdentifiers)
        }
        let displaySource: ClipboardSource
        if provided?.bundleIdentifier == markerBundleID {
            displaySource = ClipboardSource(appName: provided?.appName, bundleIdentifier: markerBundleID)
        } else {
            displaySource = ClipboardSource(bundleIdentifier: markerBundleID)
        }
        return SourceMetadata(displaySource: displaySource, bundleIdentifiers: bundleIdentifiers)
    }

    private func capture(
        items: [NSPasteboardItem],
        typesByItem: [[NSPasteboard.PasteboardType]],
        source: ClipboardSource?
    ) -> PasteboardReadResult {
        var capturedItems = [CapturedItem]()
        for (item, types) in zip(items, typesByItem) {
            guard types.contains(where: isSupportedCaptureType) else {
                return .skipped(.unsupported)
            }
            guard let captured = capture(item: item, types: types) else {
                return .skipped(.malformed)
            }
            capturedItems.append(captured)
        }

        guard let first = capturedItems.first else {
            return .skipped(.empty)
        }

        let payload = ClipboardPayload(
            primaryTypeIdentifier: first.payload.primaryTypeIdentifier,
            representations: first.payload.representations,
            availableTypeIdentifiers: first.payload.availableTypeIdentifiers,
            plainText: first.payload.plainText,
            url: first.payload.url,
            items: capturedItems.count > 1 ? capturedItems.map(\.payload) : nil
        )
        let searchableText = capturedItems
            .flatMap(\.searchableComponents)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        let capture = ClipboardCapture(
            payload: payload,
            primaryType: first.primaryType,
            searchableText: searchableText.isEmpty ? nil : searchableText,
            source: source
        )
        return .snapshot(PasteboardSnapshot(changeCount: pasteboard.changeCount, capture: capture))
    }

    private func capture(item: NSPasteboardItem, types: [NSPasteboard.PasteboardType]) -> CapturedItem? {
        let availableTypeIdentifiers = types.map(\.rawValue)
        let fileURLType = type(.fileURL, in: types)
        let urlType = type(.URL, in: types)
        let rtfType = type(.rtf, in: types)
        let pngType = type(.png, in: types)
        let tiffType = type(.tiff, in: types)
        let textType = type(.string, in: types)

        var representations = [ClipboardRepresentation]()
        var plainText: String?
        var itemURL: URL?
        var capturedURLType: NSPasteboard.PasteboardType?
        var searchableComponents = [String]()

        if let fileURLType {
            guard let fileURL = url(from: item, type: fileURLType), fileURL.isFileURL else {
                return nil
            }
            itemURL = fileURL
            searchableComponents.append(fileURL.lastPathComponent.isEmpty ? fileURL.absoluteString : fileURL.lastPathComponent)
            guard let representation = representation(from: item, type: fileURLType, fallback: fileURL.absoluteString) else {
                return nil
            }
            representations.append(representation)
        }
        if let urlType,
           let capturedURL = url(from: item, type: urlType)
        {
            if itemURL == nil {
                itemURL = capturedURL
            }
            searchableComponents.append(capturedURL.absoluteString)
            guard let representation = representation(from: item, type: urlType, fallback: capturedURL.absoluteString) else {
                return nil
            }
            representations.append(representation)
            capturedURLType = urlType
        }

        if let rtfType {
            guard let representation = representation(from: item, type: rtfType) else {
                return nil
            }
            representations.append(representation)
        }
        if let pngType {
            guard let representation = representation(from: item, type: pngType) else {
                return nil
            }
            representations.append(representation)
        }
        if let tiffType {
            guard let representation = representation(from: item, type: tiffType) else {
                return nil
            }
            representations.append(representation)
        }
        if let textType {
            guard let text = item.string(forType: textType), !text.isEmpty,
                  let representation = representation(from: item, type: textType, fallback: text)
            else {
                return nil
            }
            plainText = text
            searchableComponents.append(text)
            representations.append(representation)
            if itemURL == nil {
                itemURL = validURL(from: text)
            }
        }

        guard let primaryTypeIdentifier = primaryTypeIdentifier(
            fileURLType: fileURLType,
            urlType: capturedURLType,
            rtfType: rtfType,
            pngType: pngType,
            tiffType: tiffType,
            textType: textType
        ) else {
            return nil
        }

        let payload = ClipboardPayloadItem(
            primaryTypeIdentifier: primaryTypeIdentifier,
            representations: representations,
            availableTypeIdentifiers: availableTypeIdentifiers,
            plainText: plainText,
            url: itemURL
        )
        let primaryType: ClipboardPrimaryType
        if fileURLType != nil {
            primaryType = .files
        } else if pngType != nil || tiffType != nil {
            primaryType = .image
        } else if rtfType != nil {
            primaryType = .richText
        } else if itemURL != nil {
            primaryType = .url
        } else if plainText != nil {
            // The history worker performs text/code classification off the main actor.
            primaryType = .text
        } else {
            primaryType = .other
        }
        return CapturedItem(payload: payload, primaryType: primaryType, searchableComponents: searchableComponents)
    }

    private func type(_ candidate: NSPasteboard.PasteboardType, in types: [NSPasteboard.PasteboardType]) -> NSPasteboard.PasteboardType? {
        types.first(where: { $0.rawValue == candidate.rawValue })
    }

    private func isSupportedCaptureType(_ type: NSPasteboard.PasteboardType) -> Bool {
        [
            NSPasteboard.PasteboardType.fileURL,
            .URL,
            .rtf,
            .png,
            .tiff,
            .string
        ].contains(where: { $0.rawValue == type.rawValue })
    }

    private func primaryTypeIdentifier(
        fileURLType: NSPasteboard.PasteboardType?,
        urlType: NSPasteboard.PasteboardType?,
        rtfType: NSPasteboard.PasteboardType?,
        pngType: NSPasteboard.PasteboardType?,
        tiffType: NSPasteboard.PasteboardType?,
        textType: NSPasteboard.PasteboardType?
    ) -> String? {
        fileURLType?.rawValue
            ?? pngType?.rawValue
            ?? tiffType?.rawValue
            ?? rtfType?.rawValue
            ?? urlType?.rawValue
            ?? textType?.rawValue
    }

    private func representation(
        from item: NSPasteboardItem,
        type: NSPasteboard.PasteboardType,
        fallback: String? = nil
    ) -> ClipboardRepresentation? {
        if let data = item.data(forType: type) {
            return ClipboardRepresentation(typeIdentifier: type.rawValue, data: data)
        }
        guard let fallback else {
            return nil
        }
        return ClipboardRepresentation(typeIdentifier: type.rawValue, data: Data(fallback.utf8))
    }

    private func url(from item: NSPasteboardItem, type: NSPasteboard.PasteboardType) -> URL? {
        let urlText = item.string(forType: type)
            ?? (item.propertyList(forType: type) as? String)
            ?? (item.propertyList(forType: type) as? URL)?.absoluteString
        guard let urlText else {
            return nil
        }
        return validURL(from: urlText)
    }

    private struct CapturedItem {
        let payload: ClipboardPayloadItem
        let primaryType: ClipboardPrimaryType
        let searchableComponents: [String]
    }

    private struct SourceMetadata {
        let displaySource: ClipboardSource?
        let bundleIdentifiers: Set<String>
    }

    private func validURL(from string: String) -> URL? {
        let candidate = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !candidate.isEmpty else {
            return nil
        }
        if let webURL = ClipboardTextClassifier.webURL(from: candidate) {
            return webURL
        }
        guard let url = URL(string: candidate),
              let scheme = url.scheme,
              !scheme.isEmpty
        else {
            return nil
        }
        return url
    }
}
